bell = "\uf0f3"
bell-slash = "\uf1f7"
calendar = "\uf073"
cogs = " "
cpu = ""
cpu_boost_off = "\uf204"
cpu_boost_on = "\uf205"
disk_drive = ""
docker = "\uf21a"
github = "\uf09b"
gpu = "\uf26c"
headphones = "\uf025"
joystick = "\uf11b"
keyboard = "\uf11c"
mail = "\uf0e0"
memory_mem = ""
memory_swap = "\uf0a0"
mouse = "\uf245"
music = "\uf001"
music_next = "\uf061"
music_pause = "\uf04c"
music_play = "\uf04b"
music_prev = "\uf060"
net_bridge = "\uf0e8"
net_down = "\u2b07"
net_loopback = "LO"
net_modem = "\uf095"
net_up = "\u2b06"
net_vpn = "\uf023"
net_wired = "\uf0ac"
net_wireless = "\uf1eb"
notification = "\uf0a2"
ping = "\u21ba"
tasks = "\uf0ae"
time = ""
toggle_off = "\uf204"
toggle_on = "\uf205"
unknown = "\uf128"
update = "\uf062"
uptime = "\uf017"

volume_empty = "墳 "
volume_full = "墳 "
volume_half = "墳 "
volume_muted = "MUTED"
microphone_empty = "\uf130"
microphone_full = "\uf130"
microphone_half = "\uf130"
microphone_muted = "\uf131"
