idle_fg = "#d0d0ff" # base1
info_bg = "#268bd2" # blue
info_fg = "#002b36" # base03
good_bg = "#859900" # green
good_fg = "#002b36" # base03
warning_bg = "#b58900" # yellow
warning_fg = "#002b36" # base03
critical_bg = "#dc322f" # red
critical_fg = "#002b36" # base03
separator = " "

